### ISSUE TITLE
ReferenceError: File is not defined

### ISSUE THREAD

**Issue by oxmwh** [Explosion-Scratch/claude-unofficial-api#10]
Hello :wave: and thank you for this cool repo.
I'm trying to uplade a file in cli, this is what I get:
```
Welcome to the Claude CLI!
? Select a conversation: Start new conversation
? (claude-2) > summarize [README.md]
Asking claude
⠋ Thinking...Uploading file README.md
ReferenceError: File is not defined
```

**Comment by Explosion-Scratch** [comment]
You're using an older version of node.js which doesn't have support for the [File](https://developer.mozilla.org/en-US/docs/Web/API/File) object. I'm planning to add polyfills to the CLI in a bit so hang tight and I'll fix this

**Comment by oxmwh** [comment]
Thanks, you're amazing :1st_place_medal:
