### ISSUE TITLE
How to run the first demo?

### ISSUE THREAD

**Issue by Hongbin98** [Explosion-Scratch/claude-unofficial-api#14]
Thanks for your work at first!

I am newbie at this. Could you provide more descriptions about running the first demo or example?

I tried to download various versions of node.js on windows and linux, but I still can't run `const Claude = require('claude-ai');` even if I have run `npm install claude-ai` and `npm install -g claude-cli` :(

**Comment by Explosion-Scratch** [comment]
I'll need some more information to really help you, first, can you run `node --version` and give the output, then run `npm i -g claude-cli` and tell me what the output is. If your output has "EACCESS" or "error#13" or something similar retry with `sudo npm i -g claude-cli`. 

If those commands seem to work for you then run `claude --version` to check that claude's installed.

If claude is installed successfully just run `claude` to test it out
