### ISSUE TITLE
Model to use doesn’t work | Falls back to the default 

### ISSUE THREAD

**Issue by gamingflexer** [Explosion-Scratch/claude-unofficial-api#15]
The limit of messages is around 20-22 for the default model. While change through the code falls back the default & in the index,js `this.claude.defaultModel()` changing it gives null response.

```
async function get_response_to_specfic_id(ocr_data) {
    // Specify the conversation ID you want to start or join
    const conversationId = "2b70e59c-58c9-4ab7-b893-770fc262bb0f";

    // Create a conversation instance with the provided ID
    const conversation = new Conversation(claude, { conversationId });
    // console.log(ocr_data);
    // Send a message and print the response
    const response = await conversation.sendMessage(ocr_data,{model_to_use} );
    console.log(response);

    return response;
}
```

![Screenshot 2023-07-19 at 6 19 08 PM](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/50608241/4970709e-d5db-4c49-ada8-d619060148b9)

**Comment by gamingflexer** [comment]
I am using it like this `const model_to_use = 'claude-1.3';`

**Comment by Explosion-Scratch** [comment]
I'll do more testing and get back to you

**Comment by Explosion-Scratch** [comment]
Seeing the JSON completion shown here I thought you might be interested in the [JSON outputting prompt template](https://github.com/Explosion-Scratch/claude-unofficial-api/blob/main/examples/json.md)

**Comment by gamingflexer** [comment]
Yeah about the json i have written pre-processing steps. So my main goal here is using a different model through the code so i can check if the results quality drop & what is the limit for each account

**Comment by Explosion-Scratch** [comment]
@gamingflexer They've updated the API and limited the models to just Claude2, all other models return a 403 it seems like. Other models worked a few days ago, which is why I added it to the API. For me it's also not falling back to the default, but instead is returning a 403. Nothing I can do about this in the API though so I'm going to close this.

Sadge
