### ISSUE TITLE
Met error at initialization when get organization from Claude

### ISSUE THREAD

**Issue by FrankSYLi** [Explosion-Scratch/claude-unofficial-api#22]
When I trying to use it, get an error at initialization, seems Claude blocked program to access API directly, anybody can help on this? 
Error at: getOrganizations
SyntaxError: Unexpected token '<', "
        <!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
![Untitled](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/58110710/6bbe81b9-501f-4705-aade-492bb795a4f8)

**Comment by FrankSYLi** [comment]
I tried by calling via Postman, it can work normally, while always get 403 when trying by Pythong progrem, even I exactly copied all header parameters from Psotman. I also tried request.session, it doesn't work, code is as below (I marked cookie as *). 
import requests
import datetime
import uuid 
import re

now = datetime.datetime.now()
twelve_hours_ago = now - datetime.timedelta(hours=12)
print(twelve_hours_ago.strftime('%a, %d %b %Y %H:%M:%S GMT'))
datatime=twelve_hours_ago.strftime('%a, %d %b %Y %H:%M:%S GMT')

uuid_obj = uuid.uuid4()
uuid_str = str(uuid_obj)
url = "https://claude.ai/api/organizations"
session = requests.session()
main_url = 'https://claude.ai/'

# Getting the cookie
session.get(main_url)
# print(session.cookies)
cookiejar_str = str(session.cookies)
pattern =r'(__cf_bm=.*) for'
match = re.search(pattern, cookiejar_str)
cf_bm_value = match.group(1)
print(cf_bm_value)

strcookie=cf_bm_value + '; sessionKey=sk-ant-*****************'
print(strcookie)

payload = {}
headers = {
  'Date':datatime,
  'Content-Type':'application/json',
  'Connection':'keep-alive',
  'Cookie': cf_bm_value,
  'Host': 'claude.ai',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82',
  'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate, br',
  'Upgrade-Insecure-Requests': '1',
  'sec-ch-ua': '"Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"Windows"',
  #'Postman-Token': 'uuid_str',
}
response = requests.request("GET", url, headers=headers, data=payload)
print(response)
print(response.text)

**Comment by Explosion-Scratch** [comment]
Still working for me, regardless, not sure what I could to to the API to make it work better so I'll close unless you have suggestions.

<img width="475" alt="image" src="https://github.com/Explosion-Scratch/claude-unofficial-api/assets/61319150/660acc39-1d59-412b-ba26-43acf2486f26">

**Comment by FrankSYLi** [comment]
Yes, I finally identified it's an network issue, and now, it can be normally executed in Node (the program @Explosion-Scratch created can run normally now, thanks). while still cannot run correctly in Python program, I don't know why...
