### ISSUE TITLE
laf中使用报错

### ISSUE THREAD

**Issue by Lseven-zzw** [Explosion-Scratch/claude-unofficial-api#34]
<img width="1038" alt="image" src="https://github.com/Explosion-Scratch/claude-unofficial-api/assets/73870365/72d47d0f-6e52-42b8-b909-44c21180b532">

**Comment by Lseven-zzw** [comment]
错误出现在调用init方法时

**Comment by Explosion-Scratch** [comment]
Clear your cookies on `https://claude.ai`, set sessionKey to the new sessionKey and try again.
