### ISSUE TITLE
It still cannot be used in laf, do you need an external network environment? or configure proxy

### ISSUE THREAD

**Issue by Lseven-zzw** [Explosion-Scratch/claude-unofficial-api#36]
It still cannot be used in laf, do you need an external network environment? or configure proxy

**Comment by Explosion-Scratch** [comment]
What's laf

**Comment by Lseven-zzw** [comment]
https://laf.run/dashboard，A cloud function platform is also a node service. Do you need to be able to access the claude network in this environment?
