### ISSUE TITLE
The value of completion in response is empty

### ISSUE THREAD

**Issue by jackytj** [Explosion-Scratch/claude-unofficial-api#39]
![image](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/42001748/e5b2c5b3-d532-4a08-812c-d94db6b08296)

**Comment by Jarvan-via** [comment]
I'm facing the same issue.

**Comment by immatt2015** [comment]
You can try using `options.progress` function when sending message.

```
const body = [], opts = {};
opts.progress = (r) => {
    if (r.completion) {
        body.push(r.completion)
    }
}

const r = await conv.sendMessage(q, opts);
return r.completion || body.join('');
```

**Comment by Jarvan-via** [comment]
> r.completion || body.join('');

it's working for me ! Thanks

**Comment by jackytj** [comment]
> You can try using `options.progress` function when sending message.
> 
> ```
> const body = [], opts = {};
> opts.progress = (r) => {
>     if (r.completion) {
>         body.push(r.completion)
>     }
> }
> 
> const r = await conv.sendMessage(q, opts);
> return r.completion || body.join('');
> ```

Thanks
