### ISSUE TITLE
An error occurred while running the command line

### ISSUE THREAD

**Issue by 12915494174** [Explosion-Scratch/claude-unofficial-api#4]
I used Git to directly pull down the code, but when I tried to run it from the command line, I encountered the following error. Is this due to my local dependency issue?
![image](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/68487349/1c4ea53b-6542-4bf4-8657-9b4477da5e0e)

**Comment by 12915494174** [comment]
I think I have solved this problem. After I entered the cli and built Claude cli, the problem did not occur. Thank you for sharing.

**Comment by Explosion-Scratch** [comment]
You're probably using an older version of node which doesn't have the Fetch API.
