### ISSUE TITLE
The program doesn't display Claude AI's response content properly after starting.

### ISSUE THREAD

**Issue by shawokou123** [Explosion-Scratch/claude-unofficial-api#45]
Hello, thank you very much for providing such a great JavaScript tool that helps me communicate with Claude in the terminal.

However, I have a very serious problem now. After entering the program, when I'm having a conversation with Claude, the content of Claude's replies in the terminal is displayed very rapidly, and only the last word is retained

For example, when I input "how are you," Claude replies with "how are you too." However, the response "how are you" flashes briefly and ultimately only the word "too" remains in the terminal.

My system is macOS, and the installed version of Claude AI is 1.0.3.

The problematic videos are as follows. Could you please help me take a look at what the issue might be?

【video】
[https://www.youtube.com/watch?v=BCGI9aHGgdA](url)

Lastly, I want to express my gratitude for this project you've provided. It's excellent!

**Comment by rafaputraa** [comment]
same

**Comment by Explosion-Scratch** [comment]
Fixed in 91426c6
