### ISSUE TITLE
Blank Completion in response.

### ISSUE THREAD

**Issue by shaiof** [Explosion-Scratch/claude-unofficial-api#47]
The AI is able to initialize and start a conversation. It will also send messages and receive a response, however in the response the completion text or (message from ai) is blank. Going on the claude-ai webpage to view the conversation the ai actually did reply, the reply just was not sent with the response at the API.

![image](https://github.com/Explosion-Scratch/claude-unofficial-api/assets/34695315/ec181184-33ed-4e74-8e45-37c0fd63f605)

**Comment by Explosion-Scratch** [comment]
See 91426c65eefa4ba29cba527e164a60a5756a1182
