### ISSUE TITLE
Getting 403 pretty much in all APIs now

### ISSUE THREAD

**Issue by jitendra-koodo** [Explosion-Scratch/claude-unofficial-api#48]
Getting 403 pretty much in all APIs while sessionKey is working in Chrome..

  [Symbol(Response internals)]: {
    url: 'https://claude.ai/api/append_message',
    status: 403,
    statusText: 'Forbidden',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }

**Comment by Explosion-Scratch** [comment]
Try logging out and getting a new sessionKey?

**Comment by jitendra-koodo** [comment]
Yes, already tried, same issue. Can it be related to my location : I'm in India.

**Comment by Explosion-Scratch** [comment]
> Yes, already tried, same issue. Can it be related to my location : I'm in India.

Yep, really sorry, claude is only available in the US + UK for the time being
