### ISSUE TITLE
messages not being received

### ISSUE THREAD

**Issue by zuoFeng59556** [Explosion-Scratch/claude-unofficial-api#49]
Why am I not receiving replies from Claude when I send messages? Also, when using stream responses, some words are missing.
<img width="662" alt="image" src="https://github.com/Explosion-Scratch/claude-unofficial-api/assets/82700206/aabd2d2c-8908-4638-84cc-7e764ff9c978">
<img width="415" alt="image" src="https://github.com/Explosion-Scratch/claude-unofficial-api/assets/82700206/751b9cf5-ce67-4a9a-b555-de9e23f01bb9">

**Comment by callmearta** [comment]
Hey I just installed the latest version and still have this problem.

**Comment by callmearta** [comment]
Fixed it by changing if(parsed.stop_reason === 'stop_sequence') to if(parsed.stop_reason === 'stop_sequence' || parsed.stop_reason === null) in index.js

**Comment by obaltian** [comment]
@callmearta didn't help with Claude-cli :(
It doesn't even execute this line, hangs somewhere before
