### ISSUE TITLE
Fix it with a custom browser-extension that uses Webworkers and websockets!

### ISSUE THREAD

**Issue by teamgroove** [Explosion-Scratch/claude-unofficial-api#55]
This way you can use the active browser-session and transport the prompts and answers via websockets.
I'm sorry, i don't have the time to do it right now, but it should be fairly easy to implement.

**Comment by Explosion-Scratch** [comment]
But then it wouldn't work via node.js. You could also simply run the claude script on a claude.ai page.

Sorry, but this isn't planned, feel free to make a PR and I'll review it though.
