### ISSUE TITLE
how to use proxy

### ISSUE THREAD

**Issue by Reb1azzze** [Explosion-Scratch/claude-unofficial-api#56]
const claude = new Claude({
    sessionKey: myKey,
    proxy: 'http://66.94.108.138:3128'
});

async function sendRequest(prompt){
    await claude.init();
    const conversation = await claude.startConversation('Hello Claude!');
    await conversation.sendMessage(prompt);
}
sendRequest("Hello");
FetchError: invalid json response body at http://66.94.108.138:3128/api/organizations reason: Unexpected token < in JSON at position

**Comment by Explosion-Scratch** [comment]
Yeah, it's no longer working, they've blocked traffic using TLS fingerprinting. I might try to get it running again after my upcoming SAT test on Saturday
